server:
  port: 80

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/property_system01?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=utf8
      username: root
      password: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  mail:
    host: smtp.qq.com
    username: 1436786590@qq.com
    password: kbahiykwqaehfidi
#    password: GSBMYLDPOPHALGKZ

mybatis-plus:
  global-config:
    db-config:
      table-prefix: tb_
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl








